version: '3.4'
services:

  cron:
    image: jfernancordova/elasticsearch-crons:1.0.0
    environment:
      CRON_ENTRY: "* * * * * curl http://php/api/backgroundTn"
    depends_on:
    - php
    deploy:
      mode: replicated
      replicas: 1

  php:
    image: nsync-digital
    deploy:
      mode: replicated
      replicas: 1
    ports:
     - "80:80"
    volumes:
     - .:/nsync
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: nsync
      MYSQL_USER: nsync
      MYSQL_PASSWORD: nsync
      MYSQL_ROOT_PASSWORD: nsync
    volumes:
      - .docker/local-mysql-datadir:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
