version: '3.4'
services:

  cron:
    image: jfernancordova/elasticsearch-crons:1.0.0
    environment:
      CRON_ENTRY: "0 3 * * * curl http://backend/api/backgroundTn"
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 1

  backend:
    image: jfernancordova/nsync-digital:1.0.0
    ports:
      - 85:80
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      - ../backend:/nsync

  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: nsync
      MYSQL_USER: nsync
      MYSQL_PASSWORD: nsync
      MYSQL_ROOT_PASSWORD: nsync
    volumes:
      - ../db/nsync-db:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8085:8080
      - 50000:50000
    volumes:
      - ../jenkins/jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

  magento:
    image: alexcheng/magento2
    ports:
      - 97:80
    depends_on:
      - db-magento
    env_file:
      - ../magento/env/.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

  db-magento:
    image: mysql:5.6.23
    ports:
      - 13306:3306
    env_file:
      - ../magento/env/.env
    volumes:
      - ../db/magento-db:/var/lib/mysql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

