version: '3.4'
services:

  cron:
    image: jfernancordova/elasticsearch-crons:1.0.0
    environment:
      CRON_ENTRY: "0 3 * * * curl http://backend/api/backgroundTn"
    depends_on:
      - backend
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - nsync

  backend:
    image: jfernancordova/nsync-digital:1.0.0
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      labels:
        traefik.frontend.rule: "Host:nsync-digital.test"
        traefik.frontend.entryPoints: "http"
        traefik.protocol: "http"
        traefik.port: "80"
        traefik.enable: "true"
        traefik.backend.loadbalancer.stickiness: "true"
    volumes:
      - ../backend:/nsync
    networks:
      - nsync

  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: nsync
      MYSQL_USER: nsync
      MYSQL_PASSWORD: nsync
      MYSQL_ROOT_PASSWORD: nsync
    volumes:
      - nsync:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - nsync

  jenkins:
    image: jenkinsci/blueocean
    ports:
      - 8085:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - nsync

  magento:
    image: alexcheng/magento2
    depends_on:
      - db-magento
    env_file:
      - ../magento/env/.env
    deploy:
      mode: replicated
      replicas: 1
      labels:
        traefik.frontend.rule: "Host:magento-nsync-digital.test"
        traefik.frontend.entryPoints: "http"
        traefik.protocol: "http"
        traefik.port: "80"
        traefik.enable: "true"
        traefik.backend.loadbalancer.stickiness: "true"
      restart_policy:
        condition: none
    networks:
      - nsync

  db-magento:
    image: mysql:5.6.23
    ports:
      - 13307:3306
    env_file:
      - ../magento/env/.env
    volumes:
      - magento-data:/var/lib/mysql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - nsync

  elasticsearch:
    image: 'elasticsearch:5'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - ../elk/esdata:/usr/share/elasticsearch/data

networks:
  nsync:
    external: true

volumes:
  nsync:
    external: true
  jenkins-data:
    external: true
  magento-data:
    external: true